name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          envkey_NODE_ENV: staging
          envkey_DEBUG_MODE: true
          envkey_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          envkey_CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          envkey_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          envkey_STRICT_SSL: true
          envkey_DB_ENABLE: false
          file_name: .env
      - name: npm install, and test
        run: |
          npm i
          npm t
