name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          file_name: .env
      - name: Create env. file
        run: |
          touch .env
          echo NODE_ENV=staging >> .env
          echo DEBUG_MODE=true >> .env
          echo CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} >> .env
          echo CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} >> .env
          echo ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} >> .env
          echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          echo STRICT_SSL=true >> .env
          echo DB_ENABLE=false >> .env
          cat .env
      - name: npm install, and test
        run: |
          npm i
          npm t
